iforjcom/urls.py
# -*- coding: utf-8 -*-
"""iforjcom URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
# from qa import views
from game import views as game_view
from oneday import views as day_view

######GAME##########
game_patterns = [
    url(r'^$', game_view.game_index),   # 主页
    url(r'^(\d+)/$', game_view.game_index, name='game'), # 管理游戏列表
    url(r'^(\d+)/honorlist/$', game_view.game_honorlist),   # 荣誉榜单
    # url(r'^(\d+)$', game_view.game),
]

#######ONEDAY#######
day_patterns = [
    url(r'^$', day_view.index), #首页
    url(r'^addreleaseday/$', day_view.addreleaseday, name='addreleaseday'), # 发布每日一练
    url(r'^(\d+)/$', day_view.showoneday, name='showoneday'), # 展示每日一练
    url(r'^addreply/$', day_view.addreply, name='addreply'), # 评论
    url(r'^agreereply/$', day_view.agreereply, name='agreereply'), # 赞同评论

    # url(r'^')
]


urlpatterns = [
    url(r'^$', 'qa.views.index', name='index'),
    url(r'^qntoken/$','qa.views.qntoken'),
    url(r'^top/$', 'qa.views.top'),
    url(r'^login/$', 'qa.views.login'),
    url(r'^logout/$', 'qa.views.logout'),
    url(r'^register/$', 'qa.views.register', name='register'),                  # 注册
    url(r'^question/(\d+)$', 'qa.views.getquestion', name='question'),          # 问题
    url(r'^search/$', 'qa.views.search'),
    url(r'^programmer/(\d+)$', 'qa.views.programmer', name='programmer'),

    url(r'^agreeanswer/$','qa.views.agree_answer'), # ajax提交 赞同的回答
    url(r'^validate/(\w+)$', 'qa.views.validate'),   # 验证用户

    url(r'^askquestion/$', 'qa.views.askquestion'),



    url(r'^commit/post/addanswer$', 'qa.views.commit_post_add'),    # 提交答案
    url(r'^commit/post/updateanswer$','qa.views.commit_post_update'),   #

    url(r'^commit/post/getcomment$', 'qa.views.getcomment'),  # 废除
    url(r'^commit/post/addcomment$', 'qa.views.addcomment'),   # 提交答案

    #url(r'^test/$','qa.views.test'),    # test markdown
    url(r'^about/', 'qa.views.about_us'),   # 关于我们

    url(r'^admin/', include(admin.site.urls)),


    url(r'^about/', 'qa.views.about_us'),

    url(r'^uploadImage$', 'qa.views.uploadImage', name="uploadImage"),
    url(r'^follow/(\d+)$', 'qa.views.follow', name='follow'),
    url(r'^unfollow/(\d+)$', 'qa.views.unfollow', name='unfollow'),
    url(r'^edit-profile/$', 'qa.views.editProfile', name="edit-profile"),

    url(r'^verificationcode/$', 'qa.views.verificationcode', name="verificationcode"),

    ######GAME##########
    url(r'game/', include(game_patterns, namespace='game')),
    ####################
    ######ONEDAY########
    url(r'day/', include(day_patterns, namespace='day')),
    ####################
]

qa/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib import admin

# Create your models here.


class User(models.Model):
    """用户表"""
    name = models.CharField(max_length=80, unique=True)  # 名字
    psd = models.CharField(max_length=127)   # 密码
    email = models.CharField(max_length=254, unique=True)
    register_time = models.DateTimeField(auto_now_add=True) # 注册时间
    last_time = models.DateTimeField(auto_now=True)     # 最后次登陆时间
    is_veri = models.BooleanField(default=False)    # 是否验证过
    level = models.CharField(max_length=36, blank=True, null=True) # 用户等级
    vericode = models.CharField(max_length=40,  null=True, blank=True)  # 验证码编码,发送到邮箱验证
    real_ip = models.GenericIPAddressField(null=True, blank=True)  # 注册时的ip地址
    # url = models.CharField(max_length=127) # 存储成好看的拼音
    introduction = models.CharField(max_length=127, null=True, blank=True) # 简介
    image = models.URLField(null=True, blank=True)   # 头像
    login_error = models.PositiveSmallIntegerField(default=0)   # 当错误登陆+1
    agree_num = models.IntegerField(default=0)  # 赞同数(当问答问题的时候被赞+1)
    viewed = models.PositiveIntegerField(default=0)   # 被浏览次数
    # 关注,自引用关系
    following = models.ManyToManyField("self", symmetrical=False, related_name="follower")

    def __unicode__(self):
        return self.name


class QuestionType(models.Model):
    """问题类型 比如 django/爬虫"""
    name = models.CharField(max_length=15, null=True)

    def __unicode__(self):
        return self.name


class Question(models.Model):
    """问题表"""
    user = models.ForeignKey(User)
    title = models.CharField(max_length=127)
    text = models.TextField()
    q_datetime = models.DateTimeField(auto_now_add=True) # 创建时间
    q_times = models.PositiveSmallIntegerField(default=0)   # 回复数量
    # 新增赞同数量
    q_type = models.ForeignKey(QuestionType, null=True, blank=True) # 问题类型

    class Meta:
        ordering = ('-q_datetime',)

    def __unicode__(self):
        return self.title


class Answer(models.Model):
    """答案表"""
    question = models.ForeignKey(Question)
    user = models.ForeignKey(User)  # 回答者
    text = models.TextField()   # 答案
    agree_user = models.ManyToManyField(User, related_name='answer_user')  # 赞同的人
    agree_num = models.SmallIntegerField(default=0)  # 赞同人的数量
    a_time = models.DateTimeField(auto_now_add=True)    # 创建时间
    weight = models.PositiveSmallIntegerField(null=True)    # 权重.
    waring = models.PositiveSmallIntegerField(null=True)    # 有人举报+1

    def __unicode__(self):
        return "%s" % self.text


class Comment(models.Model):
    """评论"""
    user = models.ForeignKey(User)
    text = models.TextField()
    c_time = models.DateTimeField(auto_now_add=True) # 创建时间
    answer = models.ForeignKey(Answer)

    def __unicode__(self):
        return self.text


admin.site.register((User, Question , Answer, QuestionType))

qa/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from form import LoginForm, RegisterForm, QuestionForm, AnswerForm, UpAnswerForm, UploadImageForm, EditProfileForm
from models import User, Question, Answer, QuestionType, Comment
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.http import JsonResponse

import hashlib
import tempfile

from django.utils.timezone import utc
from PIL import Image, ImageDraw, ImageFont


import datetime

from mypaginator import MyPaginator, EmptyPage, PageNotAnInteger
import qiniu, os
from config import ACCESS_KEY, SECRET_KEY, BUCKET_NAME, HOSTNAME, EMAIL_SALT, IMAGE_BASE_PATH, \
                                    IMAGE_APPLICATION_PATH, DEFAULT_IMAGE_PATH, FONT_PATH
from send_email import sendMail

from cStringIO import StringIO
import random
# Create your views here.


def index(request):
    """Q&A首页"""
    name =request.session.get('name')

    # 显示最新
    questions = Question.objects.all()
    # 分页
    paginator  = MyPaginator(questions, 10)

    page = request.GET.get('page')
    try:
        paginator.page(page)
    except PageNotAnInteger:
        paginator.page(1)
    except EmptyPage:
        paginator.page(paginator.num_pages)
    gol_error = request.GET.get('error')  # 全局变量
    if name:
        # 当登陆时传递名字
        return render(request, 'index.html', {'questions': paginator, 'name': name.split("&")})

    return render(request, 'index.html', {'questions': paginator, 'error': gol_error})


def top(request):
    """TOP"""
    name = request.session.get('name')
    qtype = request.GET.get('type')

    questions = Question.objects.all().order_by('-q_times')
    # 分页
    paginator = MyPaginator(questions, 10)
    page = request.GET.get('page')
    try:
        paginator.page(page)
    except PageNotAnInteger:
        paginator.page(1)
    except EmptyPage:
        paginator.page(paginator.num_pages)
    gol_error = request.GET.get('error')
    if name:
        # 当登陆时传递名字
        return render(request, 'index.html', {'questions': paginator, 'name': name.split("&")})

    return render(request, 'index.html', {'questions': paginator, 'error': gol_error})


def getquestion(request, n):
    """问题页面"""
    try:
        questions = Question.objects.get(id=n)
    except:
        raise Http404('错误的url')
    answers = questions.answer_set.all()
    name = request.session.get('name')
    if name:
        # 当登陆时传递名字
        user = User.objects.get(name=name.split("&")[0])
        followings = user.following.all()
        fans = user.follower.all()
        following_count = len(followings)
        followed_count = len(fans)
        answered = Answer.objects.filter(user=user).filter(question=questions)
        # a = Answer.objects.get(user=user)

        if answered:
            # 如果回答过了传递用户id
            return render(request,'question.html', {'questions': questions,
                                                    'answers': answers,
                                                    'name': name.split("&"),
                                                    'answered': user.id})
        else:
            # 没回答过显示文本编辑框
            return render(request,'question.html', {'questions': questions,
                                                    'answers': answers,
                                                    'name': name.split("&")})
    else:
        # 没登陆
        return render(request,'question.html', {'questions': questions,
                                                'answers': answers})


def commit_post_add(request):
    """ajax提交答案"""
    name = request.session.get('name')
    form = AnswerForm(request.POST)
    if request.method == "POST" and name and form.is_valid():
        data = form.cleaned_data
        qid = data['qid']
        text = data['text']
        # text = html.replace('<', '&lt;').replace('>', '&gt;') #待改
        question = Question.objects.get(id=int(qid))
        # 答案数 + 1
        question.q_times += 1
        question.save()
        # 保存到数据库
        user = User.objects.get(name=name.split("&")[0])
        answer = Answer(user=user, question=question, text=text)
        answer.save()
        # 待修改
        return HttpResponse('ok')
    else:
        return HttpResponse('error')


def commit_post_update(request):
    """ajax更新答案"""
    name = request.session.get('name').split("&")
    form = UpAnswerForm(request.POST)

    if request.method == "POST" and name and form.is_valid():
        data = form.cleaned_data
        aid = data['get_id']
        text = data['text']
        answer = Answer.objects.get(id=aid)
        if answer:
            answer.text = text
            answer.save()
            return JsonResponse({'status': 'ok'})
    else:
        return HttpResponse('ERROR')


def login(request):
    """登陆只接受POST,无法正常访问"""
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            u_email = data['email']
            u_psd = data['password']
            # return render(request, 'index.html',{'login_error':request.META.get('HTTP_REFERER', '/')})
            try:
                user = User.objects.get(email=u_email)
                # 登录错误检查
                login_error = user.login_error
                last_time = user.last_time
                now = datetime.datetime.utcnow().replace(tzinfo=utc)
                del_s = now - last_time
                wait_time = (login_error - 3) * 5
                if del_s.seconds > wait_time * 60:
                    # 如果相差的时间大于必须等待的秒数,可以正常登录一次
                    pass
                else:
                    if login_error > 3:
                        return HttpResponse('由于错误次数过多,已经帮您锁住.请%s分钟之后再试'% wait_time)
                if user.psd != hashlib.sha1(u_psd).hexdigest():
                    # 如果密码不正确查询错误次数
                    user.login_error += 1
                    user.save()
                    # remainder = 4 - login_error
                    return HttpResponse('邮箱或密码错误')
                else:
                    # 检查是否验证了邮箱
                    if not user.is_veri:
                        return HttpResponse("可以麻烦您验证一下邮箱么⊙︿⊙")
                    else:
                        # 登录成功
                        name = user.name
                        request.session['name'] = name + "&" + str(user.id)  # 总觉得空格不太好
                        # print name
                        user.last_time = 0
                        user.save()
                        return JsonResponse({'status': 'ok'})
            except User.DoesNotExist:
                return HttpResponse('邮箱或密码错误')
        else:
            return HttpResponse('邮箱或密码错误')


def register(request):
    """注册用户"""
    if request.method == "POST":
        f = RegisterForm(request.POST)

        if f.is_valid():
            vari = request.POST.get('vari')
            if not vari or vari != request.session.get("captcha"):
                # return render(request, "register.html", {'errors': f.errors})
                return render(request, "register.html", {'errors': '错误的验证码'})
            name = f.cleaned_data["name"]    # 用户名
            email = f.cleaned_data["email"]  # 邮箱
            psd = f.cleaned_data["psd"]  # 密码
            real_ip = request.META['REMOTE_ADDR']   # ip
            introduction = f.cleaned_data["introduction"]
            vericode = hashlib.sha1(email+EMAIL_SALT).hexdigest()
            user = User.objects.create(name=name, email=email, psd=hashlib.sha1(psd).hexdigest(),
                                       introduction=introduction, vericode=vericode, real_ip=real_ip,
                                       image=DEFAULT_IMAGE_PATH)

            if sendMail([email], '验证邮箱', u"""{username},你好,IFORJ是致力于python的网络问答社区,帮助你寻找答案,分享知识。iforj是由用户可以根据自身的需
求,有针对性地提出问题;同时,这些答案又将作为搜索结果。你可以搜索类似的问题，问题被分为，爬虫，数据分析，django，scrapy，
python语法等基础分类，你可以按着分类搜索相关的问题。我们以打造最活跃的python问答平台为目的，很高兴为您提供便捷的服务。
如果有好的意见和建议，欢迎联系我们
<a href="http://{HOSTNAME}/validate/{vericode}">验证邮箱</a>""".format(username=name,
                    HOSTNAME=HOSTNAME, vericode=vericode)):
                del request.session['captcha']
                user.save()
            else:
                pass  # 邮件发送失败
            return HttpResponseRedirect("/")
        else:
            return render(request, "register.html", {'errors': f.errors})
    return render(request, "register.html")


def editProfile(request):
    name = request.session.get("name")
    if name:
        user_id = name.split("&")[1]
    else:
        user_id = None
    user = User.objects.get(id=user_id)
    old_email = user.email
    old_introduction = user.introduction

    if request.method == "POST":
        f = EditProfileForm(request.POST)
        if f.is_valid():
            new_email = f.cleaned_data["new_email"]
            new_introduction = f.cleaned_data["new_introduction"]
            user.email = new_email
            user.vericode = hashlib.sha1(new_email+EMAIL_SALT).hexdigest()
            user.introduction = new_introduction
            user.save()
            return HttpResponseRedirect("/programmer/%s" % str(user_id))
        else:
            return render(request, "edit-profile.html", {'errors': f.errors, "name": name.split("&")})
    return render(request, "edit-profile.html", {"email": old_email, "introduction": old_introduction,
                                                 "name": name.split("&")})


def mypaginator(request, questions, n):
    paginator  = MyPaginator(questions, n)
    page = request.GET.get('page')
    try:
        paginator.page(page)
    except PageNotAnInteger:
        paginator.page(1)
    except EmptyPage:
        paginator.page(paginator.num_pages)
    return paginator


qa/templates/askquestion.html
{% extends 'base.html' %}
{% block css %}
    {#七牛云支持#}
    <script src="//cdn.bootcss.com/plupload/2.1.7/plupload.full.min.js"></script>
    <script src="http://jssdk.demo.qiniu.io/js/qiniu.js"></script>

    {#富文本支持#}
    {% load staticfiles %}
    <script src="/static/js/epiceditor.js"></script>
{% endblock css %}

{% block content %}
    <div class="col-md-6 col-md-offset-3" >
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input id="qtitle" type="text" class="form-control" maxlength="127" placeholder="问题">
        </div>
        <br/>


        <div class="input-group">
            <span class="input-group-addon">标签</span>
            <input id="qtype" type="text" class="form-control span" placeholder="输入标签">
        </div>

        <br/>

        <div id="epiceditor"></div>
        <br/>


        <div id="container">
            <a class="btn btn-default btn-lg " id="pickfiles" href="#" >
                <i class="glyphicon glyphicon-plus"></i>
                <sapn>选择文件</sapn>
            </a>
        </div>
        <button id="qsubmit" type="button" class="btn btn-default pull-right">提交</button>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/js/upimage.js"></script>
    <script>
        var editor = new EpicEditor().load();

        {#提交问题#}
        $("#qsubmit").click(function() {
            var qtitle =$("#qtitle").val();
            var qtype = $('#qtype').val();
            var theContent = editor.exportFile();

            $.ajax({
                type:'POST',
                url:'/askquestion/',
                data:{"title":qtitle,"text":theContent, "q_type":qtype},
                dataType:'json',
                success:function(){
                    window.location.href="/";
                },
                error:function(){
                    window.location.reload();
                }
            });
            // alert(theContent)
        });
    </script>
{% endblock %}

qa/templates/base.html
<!DOCTYPE html>
<html>

<head lang="Zh-cn">
    <meta charset="UTF-8">
    <meta name="keywords" content={% if keywords %}{% else %}"python,问答网站,python社区"{% endif %}>
    <meta name="description" content={% if description %}{% else %}"python社区"{% endif %}>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Python社区{% endblock %}</title>

    <link rel="icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="/static/css/search.css">
    <link rel="stylesheet" type="text/css" href="/static/css/profile.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>


{#    <link href="http://wiki.jikexueyuan.com/project/bootstrap4/dist/css/bootstrap.min.css" rel="stylesheet">#}
{#    <link href="http://wiki.jikexueyuan.com/project/bootstrap4/assets/css/docs.min.css" rel="stylesheet">#}
{#    <link href="http://wiki.jikexueyuan.com/project/bootstrap4/assets/css/custom.css" rel="stylesheet">#}

    {% load staticfiles %}
    <style>
        {#        body{#}
        {#            background-image:url(/static/img/concrete_seamless.png);#}
        {#        }#}
    </style>
    {% block css %}

    {% endblock css %}
</head>

<body>

{% include 'nav.html' %}

{% block content %}
    <div>这里是默认内容，所有继承自这个模板的，如果不覆盖就显示这里的默认内容。</div>
{% endblock %}


{% block bootstrapjs %}
    <script src="http://ajax.useso.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
{% endblock %}

{% block js %}
{% endblock js %}



</body>
</html>

qa/templates/edit-profile.html
{% extends 'base.html' %}

{% load some_change_errors %}

{% block content %}
    <div class="container">
        <form class="form-horizontal" role="form" method="post" action="{% url 'edit-profile' %}">
            <fieldset>
                <div>
                    <legend class="legend">
                        编辑资料
                    </legend>
                </div>
                <br>
                {{ errors|beautify_errors }}
                <br>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="email">邮箱</label>
                    <div class="col-sm-4">
                        <input class="form-control" name="new_email" type="text" value="{{ email }}">
                        <span class="help-block">请输入您的邮箱</span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="intro">自我介绍</label>
                    <div class="col-sm-4">
                        <textarea class="form-control" name="new_introduction">{{ introduction }}</textarea>
                        <span class="help-block">介绍一下自己吧</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" class="btn btn-primary" style="float:left;" value="提交" id="submit">
                    </div>
                </div>
            </fieldset>
            {% csrf_token %}
        </form>
    </div>
{% endblock %}


qa/templates/programmer_following.html
{% extends 'base.html' %}

{% block content %}
{% include 'profile-header.html' %}
<div class="profile-section-wrap profile-answer-page">
    <div class="profile-section-nav">
        <nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-user"></span> </a>
   </div>
   <div>
      <ul class="nav navbar-nav">
         <li><a href="?q=questions">问题&nbsp;{{ questions_count }}</a></li>
         <li class="active"><a href="?q=following">关注&nbsp;{{ following_count }}</a> </li>
          <li><a href="?q=fan">粉丝&nbsp;{{ followed_count }}</a> </li>
      </ul>
   </div>
</nav>
    </div>

    <div class="section-detail">
        <div class="profile-section-head" style="display:block;">
            <div class="profile-section-name"><p style="float:left;margin-left:15px;"><strong>{{ user.name }}</strong>&nbsp;关注的人</p></div>
        </div>
        <div style="color:#3C3C3C">
            {% for following in followings %}
                {{ following.name }}&nbsp;
            {% endfor %}
        </div>
    </div>
</div>

{% include 'profile-footer.html' %}

{% endblock %}




qa/templates/search.html
{% extends 'base.html' %}
{% block content %}

    <div class="col-md-6 col-md-offset-3">
        <ul class="nav nav-tabs">
            <li {% if flag == 'question' %}class="active"{% endif %} id='question'><a href="/search?type=question&q={{ q }}">问题</a></li>
            <li id='people' {% if flag == 'people' %}class="active"{% endif %}><a href="/search?type=people&q={{ q }}">用户</a></li>
            <li id='topic' {% if flag == 'topic' %}class="active"{% endif %}><a href="/search?type=topic&q={{ q }}">话题</a></li>

        </ul>
    </div>
    <br/>




    <div id="users" class="col-md-6 col-md-offset-3" style="disabled:none;">
        <ul class="list users">
            {% for user in users %}
                <li class="user item">
                    <div class="panel">
                        <div class="top">
                            <div class="panel-heading">
                                <a href="#" class="left avatar-link">
                                    <img src="{{ user.image }}" alt="{{ user }}" class="avatar" style="float:left;width:60px;heigth:60px;">
                                </a>
                                <div class="info">
                                    <a href="/programmer/{{ user.id }}"><strong>{{ user.name }}</strong></a>
                                    <p>{{ user.introduction }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
{#                            <a href="#" class="btn-sm btn-primary" style="text-decoration: none;">#}
{#                                关注</a>#}
                            <div class="panel-foot">
                                <strong>{{ user.question_set.count }}</strong>&nbsp;问题&nbsp;&nbsp;
                                <strong>{{ user.answer_set.count }}</strong>&nbsp;回答&nbsp;&nbsp;
                                <strong>{{ user.agree_num }}</strong>&nbsp;赞同数
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="col-md-6 col-md-offset-3" id="topics" style="disabled:none;">
        {% for topic in topics %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title" style="color:#337ab7">

                        <a href="#">{{ topic.name }}</a>
                    </h3>
                </div>
                <div class="panel-body">
{#                    <a href="#" class="btn-sm btn-primary" style="text-decoration: none;">关注</a>#}
                    共{{ questions_num }}问题
                </div>
            </div>
        {% endfor %}
    </div>
    
    
    <div class="col-md-6 col-md-offset-3" >
        {% for question in questions.page_list %}
    
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title" style="color:#337ab7;">
                        <a href="{% url 'question' question.id %}" ><b>{{ question.title }}</b></a>
    
                        <a href="/search/?type=topic&q={{ question.q_type }}">
                            <span class="label label-default">{{ question.q_type }}</span>
                        </a>
                    </h1>
    
                </div>
                <div class="panel-body">
                    回复:{{ question.q_times }}
                </div>
            </div>
        {% endfor %}
    </div>
 
    {% if questions.num_pages > 1 %}
        <div class="col-md-6 col-md-offset-5" >
            <ul class="pagination">
    
                <li><a href="?page=1">&laquo;</a></li>
    
                {%  for i in questions.page_range %}
                    <li {% ifequal i questions.number %}class="active"{% endifequal %}>
                        <a href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endfor %}
                <li><a href="?page={{ questions.num_pages }}">&raquo;</a></li>
            </ul>
    </div>
    {% endif %}
{% endblock %}


